package com.mindmap.jane.domain.enumeration;

public enum FieldOfScienceQualifier {

    ADM("adm", "administracja (państwowa, rządowa itd.),"),
    AGROT("agrot", "agrotechnika, agrotechniczny"),
    AKUST("akust", "akustyka, akustyczny"),
    ANAT("anat", "anatomia, anatomiczny"),
    ANTROP("antrop", "antropologia, antropologiczny"),
    ARACHN("arachn", "arachnologia, arachnologiczny"),
    ARCHIT("archit", "architektura, architektoniczny"),
    ARCHEOL("archeol", "archeologia, archeologiczny"),
    ASTR("astr", "astronomia, astronomiczny"),
    ASTROL("astrol", "astrologia, astrologiczny"),
    ASTRONAUT("astronaut", "astronautyka, astronautyczny"),
    BANK("bank", "bankowość, bankowy"),
    BIBL("bibl", "biblijny"),
    BIBLIOT("bibliot", "bibliotekoznawstwo, bibliotekoznawczy"),
    BIOCHEM("biochem", "biochemia, biochemiczny"),
    BIOL("biol", "biologia, biologiczny"),
    BIUR("biur", "biurowość, biurowy"),
    BOT("bot", "botanika, botaniczny"),
    BUD("bud", "budownictwo"),
    CHEM("chem", "chemia, chemiczny"),
    CHOREOGR("choreogr", "choreografia, choreograficzny"),
    CUK("cuk", "cukiernictwo"),
    CYBERN("cybern", "cybernetyka, cybernetyczny"),
    DEMOGR("demogr", "demografia"),
    DENDR("dendr", "dendrologia, drzewoznawstwo, dendrologiczny, drzewoznawczy"),
    DRUK("druk", "drukarstwo"),
    EDUK("eduk", "edukacja, edukacyjny"),
    EKOL("ekol", "ekologia, ekologiczny"),
    EKON("ekon", "ekonomia, ekonomiczny"),
    ELEKTR("elektr", "elektryczność, elektryczny"),
    ELEKTRON("elektron", "elektronika, elektroniczny"),
    ENT("ent", "entomologia, owadoznawstwo, entomologiczny, owadoznawczy"),
    ETN("etn", "etnografia, etnograficzny"),
    EZOT("ezot", "ezoteryka"),
    FANT("fant", "fantastyka"),
    FAMR("farm", "farmacja, lekoznawstwo, farmakologia, farmaceutyczny, farmakologiczny"),
    FELINOL("felinol", "felinologia, felinologiczny"),
    FILM("film", "filmologia, filmoznawstwo, filmologiczny, filmoznawczy, filmowy"),
    FILOZ("filoz", "filozofia, filozoficzny"),
    FITOPATOL("fitopatol", "fitopatologia, fitopatologiczny"),
    FIZ("fiz", "fizyka, fizyczny"),
    FIZJ("fizj", "fizjologia, fizjologiczny"),
    FLIS("flis", "flisactwo"),
    FOLK("folk", "folklor"),
    FONET("fonet", "fonetyka, fonetyczny"),
    FOT("fot", "fotografia"),
    FRYZ("fryzj", "fryzjerstwo, fryzjerski"),
    GAST("gastr", "gastronomia, gastronomiczny"),
    GEOD("geod", "geodezja, geodezyjny"),
    GEOFIZ("geofiz", "geofizyka, geofizyczny"),
    GEOGR("geogr", "geografia, geograficzny"),
    GEOL("geol", "geologia, geologiczny"),
    GEOM("geom", "geometria"),
    GEND_ST("gend. st", "gender studies"),
    GORN("górn", "górnictwo, górniczy"),
    GRAM("gram", "gramatyka, gramatyczny"),
    HAND("hand", "handel, handlowy"),
    HARC("harc", "harcerski"),
    HERALD("herald", "heraldyka, heraldyczny"),
    HERP("herp", "herpetologia, herpetologiczny"),
    HIPOL("hipol", "hipologia, hipologiczny"),
    HIST("hist", "historia, historyczny, historycznie"),
    HOTEL("hotel", "hotelarstwo"),
    HUTN("hutn", "hutnictwo, hutniczy"),
    HYDROL("hydrol", "hydrologia"),
    ICHT("icht", "ichtiologia, ichtiologiczny"),
    IKONOGR("ikonogr", "ikonografia, ikonograficzny"),
    INFORM("inform", "informatyka, informatyczny"),
    JEZDZ("jeźdz", "jeździectwo, jeździecki"),
    JEZ("jęz", "językoznawstwo, językoznawczy"),
    JUBIL("jubil", "jubilerstwo, jubilerski"),
    KARC("karc", "termin karciany"),
    KARTOGR("kartogr", "kartografia, kartograficzny"),
    KOLEJ("kolej", "kolejnictwo"),
    KOMP("komp", "komputer, komputerowy"),
    KOSMET("kosmet", "kosmetyka, kosmetyczny, kosmetologia"),
    KRAW("kraw", "krawiectwo"),
    KRYM("krym", "kryminologia, kryminologiczny"),
    KRYPTOGR("kryptogr", "kryptografia, kryptograficzny"),
    KRYSTAL("krystal", "krystalografia, krystalograficzny"),
    KSIEG("księg", "księgowość, księgowy"),
    KULIN("kulin", "kulinaria, kulinarny"),
    KULT("kult", "kulturoznawstwo, wiedza o kulturze, kulturoznawczy"),
    KYNOL("kynol", "kynologia, kynologiczny"),
    LESN("leśn", "leśnictwo"),
    LITER("liter", "literatura, literaturoznawstwo, literaturoznawczy"),
    LOG("log", "logika, logiczny"),
    LOTN("lotn", "lotnictwo, lotniczy"),
    LOW("łow", "łowiectwo, łowiecki"),
    MAR("mar", "marynistyczny, marynarski, morski"),
    MASZ("masz", "maszyny, maszynoznawstwo"),
    MAT("mat", "matematyka, matematyczny"),
    MECH("mech", "mechanika"),
    MED("med", "medycyna, medyczny"),
    MELIOR("melior", "melioratywnie, melioratywny"),
    MET("met", "metaloznawstwo, metalurgia"),
    METEROL("meteorol", "meteorologia, meteorologiczny"),
    METROL("metrol", "metrologia, metrologiczny"),
    MIL("mil", "militarny, militaria"),
    MIKOL("mikol", "mikologia, mikologiczny"),
    MIKROBIL("mikrobiol", "mikrobiologiczny, mikrobiologia"),
    MINER("miner", "mineralogia, mineralogiczny"),
    MIT("mit", "mitologia, mitologiczny"),
    MIT_ARAB("mit. arab", "mitologia arabska"),
    MIT_BASK("mit. bask", "mitologia baskijska"),
    MIT_CELT("mit. celt", "mitologia celtycka"),
    MIT_CHIN("mit. chiń", "mitologia chińska"),
    MIT_EGIP("mit. egip", "mitologia egipska"),
    MIT_GERM("mit. germ", "mitologia germańska"),
    MIT_GR("mit. gr", "mitologia grecka"),
    MIT_POLINEZ("mit. polinez", "mitologia polinezyjska"),
    MIT_RZYM("mit. rzym", "mitologia rzymska"),
    MIT_SLOW("mit. słow", "mitologia słowiańska"),
    MIT_SUMER("mit. sumer", "mitologia sumeryjska"),
    MIT_WED("mit. wed", "mitologia wedyjska"),
    MLYN("młyn", "młynarstwo, młynarski"),
    MORS("mors", "morski"),
    MOT("mot", "motoryzacja"),
    MUZ("muz", "muzykologia, muzyka, muzykologiczny, muzyczny"),
    NAUK("nauk", "naukoznawstwo, nauka, naukoznawczy, naukowy"),
    NAWIG("nawig", "nawigacja"),
    NUMIZM("numizm", "numizmatyka, numizmatyczny"),
    OCEANOGR("oceanogr", "oceanografia, oceanograficzny"),
    ODL("odl", "odlewnictwo, przemysł odlewniczy"),
    OGROD("ogrod", "ogrodnictwo, ogrodniczy"),
    OPT("opt", "optyka, optyczny"),
    ORNIT("ornit", "ornitologia, ornitologiczny"),
    PALEOANTROP("paleoantrop", "paleoantropologia, paleoantropologiczny"),
    PALEONT("paleont", "paleontologia, paleontologiczny"),
    PEDAG("pedag", "pedagogika, pedagogiczny"),
    PLAST("plast", "plastyka"),
    POLIGR("poligr", "poligrafia"),
    POLIT("polit", "politologia, polityka, politologiczny, polityczny"),
    PRAW("praw", "prawo, prawoznawstwo, prawniczy, prawoznawczy"),
    PSYCH("psych", "psychologia, psychologiczny"),
    PSZCZ("pszcz", "pszczelarstwo, pszczelarski"),
    PUBL("publ", "publikatory, charakterystyczny dla środków masowego przekazu"),
    RAD("rad", "radiofonia, radiokomunikacja, radiotechnika, radiofoniczny, radiokomunikacyjny, radiotechniczny, radiowy"),
    REG("reg", "regionalizm, regionalny"),
    REL("rel", "religioznawstwo, religia, religioznawczy, religijny"),
    ROLN("roln", "rolnictwo, rolniczy"),
    RYB("ryb", "rybołówstwo, rybacki"),
    RZEM("rzem", "rzemiosło, rzemieślniczy"),
    SEKS("seks", "seksuologia, seksuologiczny"),
    SF("s.f", "fantastyka naukowa, ang. „science fiction”"),
    SOCJOL("socjol", "socjologia, socjologiczny"),
    SPEC("spec", "termin specjalistyczny"),
    SPELEOL("speleol", "speleologia, speleologiczny"),
    SPOL("społ", "społeczny"),
    SPORT("sport", "termin sportowy"),
    SPOZ("spoż", "spożywczy"),
    STAT("stat", "statystyka, statystyczny"),
    STOMAT("stomat", "stomatologia"),
    STUD("stud", "studencki"),
    SYST("syst", "systematyka"),
    SZACH("szach", "szachy, pojęcie szachowe"),
    SZKOLN("szkoln", "szkolnictwo, szkolny"),
    SZT("szt", "sztuka"),
    TAUR("taur", "tauromachia"),
    TEATR("teatr", "teatrologia, teatr, teatrologiczny, teatralny"),
    TRCHN("techn", "technologia, technika, techniczny"),
    TELEGR("telegr", "telegrafia, telegraficzny"),
    TELEKOM("telekom", "telekomunikacja, telekomunikacyjny"),
    TELEW("telew", "telewizja, telewizyjny"),
    TEOL("teol", "teologia, teologiczny"),
    TOPOGR("topogr", "topografia, topograficzny"),
    TURYST("turyst", "turystyka, turystyczny"),
    TYPOGR("typogr", "typografia"),
    URB("urb", "urbanistyka, urbanistyczny"),
    WET("wet", "weterynaria, weterynaryjny"),
    WEDK("wędk", "wędkarstwo"),
    WIOSL("wiośl", "wioślarstwo"),
    WLOK("włók", "włókiennictwo"),
    WOJSK("wojsk", "wojskowość, wojskowy"),
    ZARZ("zarz", "zarządzanie"),
    ZAW("zaw", "zawodowy"),
    ZEG("zeg", "zegarmistrzostwo, zegarmistrzowski"),
    ZOOL("zool", "zoologia, zoologiczny"),
    ZOOTECHN("zootechn", "zootechnika, zootechniczny"),
    ZEGL("żegl", "żeglarstwo, żegluga, żeglarski"),
    ZYD("żyd", "żydowski");

    private final String template;
    private final String meaning;

    FieldOfScienceQualifier(String template, String meaning) {
        this.template = template;
        this.meaning = meaning;
    }
}
